[package]
name = "rml"
version = "0.1.0"
edition = "2024"

[dependencies]
rmlx.workspace = true
tower-lsp.workspace = true
lexer-core.workspace = true
pest.workspace = true
pest_derive.workspace = true
url.workspace = true