[package]
name = "rmlx-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-lsp.workspace = true
logos.workspace = true
chumsky.workspace = true

lexer-utils.workspace = true
url.workspace = true
