[package]
name = "rmlx-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer-utils.workspace = true

tower-lsp.workspace = true
logos.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
reqwest.workspace = true
