[package]
name = "type-ml-definitions"
version = "0.1.0"
edition = "2024"


[dependencies]
lexer-core.workspace = true
thiserror.workspace = true
url.workspace = true
reqwest.workspace = true
enum_dispatch.workspace = true
regex.workspace = true
pest.workspace = true
pest_derive.workspace = true