[package]
name = "type-ml"
version = "0.1.0"
edition = "2024"

[dependencies]
type-ml-definitions.workspace = true
lexer-core.workspace = true
pest.workspace = true
pest_derive.workspace = true
url.workspace = true