[package]
name = "rml-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
rml-lexer.workspace = true
rmlx-lexer.workspace = true
lexer-utils.workspace = true

ron.workspace = true
tokio.workspace = true
tower-lsp.workspace = true
serde.workspace = true
logos.workspace = true
