name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Install llvm-tools
        run: rustup component add llvm-tools-preview

      - name: Install grcov
        run: |
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 \
            | tar jxf -
          sudo mv grcov /usr/local/bin/

      - name: Build with coverage flags
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Generate coverage report
        run: |
          mkdir -p target/coverage/html
          grcov target/coverage \
            --binary-path ./target/debug/ \
            -s . \
            -t html \
            --branch \
            --ignore-not-existing \
            --ignore "/*" \
            -o target/coverage/html

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: target/coverage/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/coverage/html
          publish_branch: gh-pages
