name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install llvm-tools
        run: rustup component add llvm-tools

      - name: Install grcov
        run: cargo install grcov --locked

      - name: Build
        env:
          RUSTFLAGS: -Cinstrument-coverage
        run: cargo build
      - name: Test
        env:
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
          RUSTFLAGS: -Cinstrument-coverage
        run: cargo test

      - name: Generate coverage report
        run: |
          mkdir -p target/coverage/html
          grcov $(find . -name "grcov-*.profraw" -print) \
            --binary-path ./target/debug/ \
            -s . \
            -t html \
            --branch \
            --ignore-not-existing \
            --ignore "/*" \
            -o target/coverage/html
